server:
  port: 8761

eureka:
  renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 0
  client:
    register-with-eureka: false
    fetch-registry: false
